version: "3.9"
services:
  wp:
    build:
      context: .
      args:
        DOMAIN: example.com
        CAPWD: ca_password
        XDEBUG: ${WORDPRESS_XDEBUG}
    hostname: example.com
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "443:443"
    volumes:
      - ./wp:/var/www/html
      - ./log:/var/log
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpusr
      WORDPRESS_DB_PASSWORD: wppwd
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: /var/log
  db:
    image: mariadb
    hostname: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.db:/var/lib/mysql
      - /var/log:/var/log
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpusr
      MARIADB_PASSWORD: wppwd
